# Generated by Django 3.0.8 on 2020-07-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_dicount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dicount_price',
            new_name='discount_price',
        ),
    ]
