# Generated by Django 3.0.8 on 2020-07-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200728_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a text description you mana nnsjsncksnkccknkc ekndknedkdmcoewjoiwe cknekneoecmmckcmmddkd xnjnejnejneneknckcek ncjncne'),
            preserve_default=False,
        ),
    ]
