# Generated by Django 3.0.8 on 2020-08-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200804_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='image',
        ),
    ]
